Proyecto/routes/web.php
<?php

use App\Faculty;
use App\Program;




/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/*ruta para la pagina de inicio"*/
/*Route::get('/', function(){
	$user = Auth::user();

	return $user;
});*/


Route::resource('/facultades', 'facultiesController');
Route::resource('/programas', 'programsController');
Route::resource('/titulos', 'titlesController');




Route::post('facultades/store', 'facultiesController@store')->name('facultades.store');






/* uno a uno id de programa a facultadad*/
Route::get('/programas/{id}/facultad', function($id){
	return Program::find($id)->faculty->Name;
});

/*uno a uno id de facultad a programa*/ 
Route::get('/facultad/{id}/programas', function($id){
	return Faculty::find($id)->program->Name;


});


/*uno a varios (de la id de faculytadad a sus respectivos programas)*/ 
Route::get('/programas_f', function(){
	return $programs = Faculty::find(1)->programs;

});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Proyecto/app/Program.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Program extends Model
{

	protected $fillable=[

    	"Name",
    	"Description"

    ];

    public function faculty(){

    	return $this->belongsTo("App\Faculty");

    }
}

Proyecto/app/Http/Controllers/programsController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Program;
use App\Faculty;

class programsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(){

        $programs = Program::all();
        $faculties = Faculty::all();

        return view("programs/program", compact('programs', 'faculties'));
    }
    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return "404";
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        /*Recibe los datos del formulario en la ruta programas (archivo -> programs.blade.php) para crear datos en la tabla -> faculties*/ 
        $program = new Program;
        $program->Name = $request->Name;
        $program->faculty_id = $request->faculty_id;
        $program->Description = $request->Description;
        $program->save();

        return redirect('/programas');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $program = Program::find($id);
        $faculties = Faculty::all();

        //vista 
        return view('programs/show', compact('program', 'faculties'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $program = Program::find($id);

        $program->update($request->all());

        return redirect("/programas/{$id}");
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $program = Program::find($id);

        $program->delete();

        return redirect("/programas"); 
    }
}

Proyecto/resources/views/programs/program.blade.php
@extends('layouts/layout')

@section('title', 'Programas') <!-- titulo de la de la pestaña -->

@section('content')

	<!-- formulario para crear nuevos programas. Los datos se envían a la misma ruta y los toma la public function store del controllador (programsController) para crear nuevos registros en la tabla faculties-->
	<form method="post" action= " {{route('programas.store')}} " >
		{{csrf_field()}} 
		<input type="text" name="Name"><br>
		<select name="faculty_id">
			@foreach($faculties as $faculty)
				<option value="{{ $faculty->id }}">{{ $faculty->Name }}</option>
			@endforeach
  		</select>
		<textarea name="Description" ></textarea>
		
		<input type="submit" name="send" value="Enviar">
	</form>

	<!-- este foreach muestra los datos de la tabla faculties--> 
	<nav>
		@foreach($programs as $program)
			<ul><a href="/programas/{{ $program->id }}">{{$program->Name}}</a> name</ul>
		@endforeach
	</nav>
	
@endsection

Proyecto/resources/views/programs/show.blade.php
@extends('..layouts/layout')

@section('title', '') <!-- titulo de la de la pestaña -->

@section('content')
	
	<h1>Editar</h1>

	<!-- formulario para enviar datos actualizados de una facultad ya existente. Los datos se envían a la misma ruta y los toma la public function edit del controllador (facultiesController), para actualizar  registros en la tabla faculties-->
	<form method="post" action= "/programas/{{$program->id}}" >
		{{csrf_field()}}
		<input type="hidden" name="_method" value="PUT">
		<input type="text" name="Name" value="{{$program->Name}}"><br>
		<select name="faculty_id">
			@foreach($faculties as $faculty)
				<option value="{{ $faculty->id }}">{{ $faculty->Name }}</option>
			@endforeach
  		</select>
		<textarea name="Description" ></textarea>
		<input type="submit" name="send" value="Enviar">
	</form>

	<!-- Boton para enviar el id de la facultad y eliminarla desde public function edit en el controllador (facultiesController), de la tabla faculties --> 
	<form method="post" action= "/programas/{{$program->id}}" >
		{{csrf_field()}}
		<input type="hidden" name="_method" value="DELETE">
		<input type="submit" name="send" value="Eliminar">
	</form>

@endsection