Proyecto/routes/web.php
<?php

use App\Faculty;
use App\Program;




/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/*ruta para la pagina de inicio"*/
/*Route::get('/', function(){
	$user = Auth::user();

	return $user;
});*/


Route::resource('/facultades', 'facultiesController');
Route::resource('/programas', 'programsController');
Route::resource('/titulos', 'titlesController');




Route::post('facultades/store', 'facultiesController@store')->name('facultades.store');






/* uno a uno id de programa a facultadad*/
Route::get('/programas/{id}/facultad', function($id){
	return Program::find($id)->faculty->Name;
});

/*uno a uno id de facultad a programa*/ 
Route::get('/facultad/{id}/programas', function($id){
	return Faculty::find($id)->program->Name;


});


/*uno a varios (de la id de faculytadad a sus respectivos programas)*/ 
Route::get('/programas_f', function(){
	return $programs = Faculty::find(1)->programs;

});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Proyecto/app/Title.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Title extends Model
{
    protected $fillable=[

    	"Name",
    	"Description"

    ];
}

Proyecto/app/Http/Controllers/titlesController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Title;
use App\Program;

class titlesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $titles = Title::all();
        $programs = Program::all();

        return view("titles/title", compact('titles', 'programs'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request,['Name' => 'required']);
        /*Recibe los datos del formulario en la ruta titulos (archivo -> title.blade.php) para crear datos en la tabla -> titles*/ 
        $Title = new Title;
        $Title->Name = $request->Name;
        $Title->program_id = $request->program_id;
        $Title->Description = $request->Description;
        $Title->save();

        return redirect('/titulos');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $title = Title::find($id);
        $programs = Program::all();

        //vista 
        return view('titles/show', compact('title', 'programs'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $title = Title::find($id);

        $title->update($request->all());

        return redirect("/titulos/{$id}");
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $title = Title::find($id);

        $title->delete();

        return redirect("/titulos"); 
    }
}

Proyecto/resources/views/titles/show.blade.php
@extends('..layouts/layout')

@section('title', 'Titulos') <!-- titulo de la de la pestaña -->

@section('content')
	
	<h1>Editar</h1>

	<!-- formulario para enviar datos actualizados de un titulo ya existente. Los datos se envían a la misma ruta y los toma la public function edit del controllador (titlesController), para actualizar  registros en la tabla titles-->
	<form method="post" action= "/titulos/{{$title->id}}" >
		{{csrf_field()}}
		<input type="hidden" name="_method" value="PUT">
		<input type="text" name="Name" value="{{$title->Name}}">
		<br>
		<select name="program_id">
			@foreach($programs as $program)
				<option value="{{ $program->id }}">{{ $program->Name }}</option>
			@endforeach
  		</select>
  		<br>
		<textarea name="Description" ></textarea>
		<input type="submit" name="send" value="Enviar">
	</form>

	<!-- Boton para enviar el id del titulo y eliminarlo desde public function edit en el controllador (titlesController), de la tabla titles --> 
	<form method="post" action= "/titulos/{{$title->id}}" >
		{{csrf_field()}}
		<input type="hidden" name="_method" value="DELETE">
		<input type="submit" name="send" value="Eliminar">
	</form>

@endsection

Proyecto/resources/views/titles/title.blade.php
@extends('layouts/layout')

@section('title', 'Titulos') <!-- titulo de la de la pestaña -->

@section('content')

	<!-- formulario para crear nuevos programas. Los datos se envían a la misma ruta y los toma la public function store del controllador (titlesController) para crear nuevos registros en la tabla faculties-->
	<form method="post" action= " {{route('titulos.store')}} " >
		{{csrf_field()}} 
		<input type="text" name="Name"><br>
		<select name="program_id">
			@foreach($programs as $program)
				<option value="{{ $program->id }}">{{ $program->Name }}</option>
			@endforeach
  		</select>
		<textarea name="Description" ></textarea>
		
		<input type="submit" name="send" value="Enviar">
	</form>

	<!-- este foreach muestra los datos de la tabla faculties--> 
	<nav>
		@foreach($titles as $title)
			<ul><a href="/titulos/{{ $title->id }}">{{$title->Name}}</a> name</ul>
		@endforeach
	</nav>
	
@endsection